name: UNICORP
favicon: null
layout_spectrum: 0.74931
typography_spectrum: 1
title: Unicorp Global
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#56297a'
    - '#b5a1c4'
    - '#cec3d9'
    - '#8a6ba3'
  brandStrength: 0.7442458583973348
  lightness: 0.708832657430321
  saturation: 0.4418658399954438
  rhythmicContrast: 0.003186792368069291
purpose: []
