name: UNICORP
favicon: null
layout_spectrum: 0.5283854585140944
typography_spectrum: 0.7367089854087681
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7442458583973348
  lightness: 0.708832657430321
  saturation: 0.4418658399954438
  rhythmicContrast: 0.003186792368069291
purpose: []
